name: "Deploy - On branch main/release Push"
on:
  pull_request:
    branches:
      - dev
      - main

    paths-ignore:
      - '.bumpversion.cfg'
      - 'setup.py'

jobs:
  Deploy-Py-Internal-Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    container:
      image: registry.cloud.mov.ai/devops/py-buildserver:latest
      credentials:
        username: ${{secrets.PORTUS_APP_USER}} 
        password: ${{secrets.PORTUS_APP_TOKEN}} 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install requirements
      run: python3 -m pip install -r requirements.txt
    - name: Run tests
      run: python3 -m pytest

    - name: raise version
      run: bump2version build setup.py
    - name: build
      run: python3 -m build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.NEXUS_PUBLISHER_USR }}
        password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
        repository_url: https://artifacts.cloud.mov.ai/repository/pypi-experimental/

    - name: Create Github Release
      shell: bash
      run: |
        title="Release of Python component" 
        
        gh release create -p -t "$title" -n "$body" ${{ steps.vars.outputs.npm_pkg_version }}

        # add all files in the artifacts folder
        assets=()
        for asset in dist/*; do
          # do nothing if folder is empty
          if [[ $asset != "dist/*" ]]; then
            gh release upload ${{ steps.vars.outputs.npm_pkg_version }} $asset
          fi 
        done

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  # [On Pull request merge] Since the pipeline will run, have a nice communication that is not doing anything.
  Skipped:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-20.04
    container:
      image: registry.cloud.mov.ai/devops/tf-buildserver:latest
      credentials:
        username: ${{secrets.PORTUS_APP_USER}} 
        password: ${{secrets.PORTUS_APP_TOKEN}} 
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been skipped since the pull request was not approved.