name: "CI - On branch dev Push"
on:
  pull_request:
    branches:
      - dev
      - main
    paths-ignore:
      - '.bumpversion.cfg'
      - 'setup.py'
jobs:
  Test-Py-Component:
    runs-on: ubuntu-20.04
    container:
      image: registry.cloud.mov.ai/devops/py-buildserver:latest
      credentials:
        username: ${{secrets.PORTUS_APP_USER}} 
        password: ${{secrets.PORTUS_APP_TOKEN}} 

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: install requirements
      run: python3 -m pip install -r requirements.txt
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "*"
        mypy-options: "--show-error-codes"
        isort-options: "-w 100"
        django: true
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'Test-Py-Component'   # NOTE: this needs to be the same as the job name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: python3 -m pytest
    - name: build
      run: python3 -m build
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.NEXUS_PUBLISHER_USR }}
        password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
        repository_url: https://artifacts.cloud.mov.ai/repository/pypi-experimental/